"""
应用常量定义
Application Constants
"""

# 默认配置值
DEFAULT_HOST = "localhost"
DEFAULT_PORT = 10095
DEFAULT_AUDIO_FS = 16000
DEFAULT_CHUNK_SIZE = "3, 6, 3"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_TIMEOUT_SECONDS = 2

# 支持的音频源类型
SUPPORTED_AUDIO_SOURCES = ["microphone", "system_audio"]

# 音频相关常量
AUDIO_FORMAT = 16  # 16位音频
DEFAULT_CHANNELS = 2
DEFAULT_SAMPLE_RATE = 44100

# WebSocket相关常量
DEFAULT_SSL_MODE = 1
DEFAULT_ITN_MODE = 1
DEFAULT_RECOGNITION_MODE = "2pass"

# 翻译相关常量
DEFAULT_TRANSLATE_API = "http://localhost:8000/translate"
MAX_TRANSLATION_CACHE_SIZE = 1000
TRANSLATION_REQUEST_TIMEOUT = 1.2

# UI相关常量
WINDOW_TITLE = "🔊 智能语音识别翻译系统"
SUBTITLE_WINDOW_TITLE = "智能字幕显示"
DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 700
DEFAULT_SUBTITLE_WIDTH_RATIO = 0.8
SUBTITLE_BOTTOM_DISTANCE = 180

# 字体相关常量
DEFAULT_FONT_SIZE = 24
CHINESE_FONT_FAMILY = "Microsoft YaHei"
ENGLISH_FONT_FAMILY = "Arial"

# 显示时间相关常量
SHORT_SENTENCE_DISPLAY_TIME = 2000  # 2秒
MEDIUM_SENTENCE_DISPLAY_TIME = 3000  # 3秒
LONG_SENTENCE_DISPLAY_TIME = 5000   # 5秒

# 文件相关常量
LOG_FILE_NAME = "client.log"
DEFAULT_OUTPUT_DIR = None

# 文本处理相关常量
SENTENCE_END_CHARS = ['，', '。', '！', '？', '.', '!', '?', ';', '；']
PUNCTUATION_CHARS = '，。！？,.!?'

# 颜色常量（科技感配色）
TECH_CYAN = "#00ffff"
TECH_MAGENTA = "#ff00ff"
TECH_BLUE = "#0080ff"
TECH_GREEN = "#00ff80"